<?php
/**
 * This file is part of O3-Shop.
 *
 * O3-Shop is free software: you can redistribute it and/or modify  
 * it under the terms of the GNU General Public License as published by  
 * the Free Software Foundation, version 3.
 *
 * O3-Shop is distributed in the hope that it will be useful, but 
 * WITHOUT ANY WARRANTY; without even the implied warranty of 
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU 
 * General Public License for more details.
 * You should have received a copy of the GNU General Public License
 * along with O3-Shop.  If not, see <http://www.gnu.org/licenses/>
 *
 * @copyright  Copyright (c) 2022 OXID eSales AG (https://www.oxid-esales.com)
 * @copyright  Copyright (c) 2022 O3-Shop (https://www.o3-shop.com)
 * @license    https://www.gnu.org/licenses/gpl-3.0  GNU General Public License 3 (GPLv3)
 */

namespace OxidEsales\Eshop\Application\Model;

/**
 * Class Article
 *
 * IMPORTANT:
 * This class has been generated by a script and is not meant to be edited.
 * Any changes will get lost during the next script run.
 *
 * @deprecated See parent class for details.
 *
 * @package OxidEsales\Eshop\Application\Model
 */
class Article extends \OxidEsales\EshopCommunity\Application\Model\Article
{

}

/**
 * This class alias is created for backwards compatibility only.
 * The class oxarticle is deprecated since O3-Shop v6.0.0 and should not be used any more as it
 * will be removed in the future.
 * Please use \OxidEsales\Eshop\Application\Model\Article instead.
 */
class_alias(\OxidEsales\Eshop\Application\Model\Article::class, 'oxarticle');

